### ISSUE TITLE
How to train and evaluate using the generated checkpoint?

### ISSUE THREAD

**Issue by msm1089** [lengstrom/fast-style-transfer#100]
EDIT: Apologies for the long error stack and also hyperlinks somehow appeared that I cannot get rid of!

I have tried to train this to generate a style checkpoint for a favourite artwork. Unfortunately no success! I would really appreciate any help to get it to work. What happens is I get just black test images. I tried running it for only 200 iterations just to see if it would give me a black image after finishing training also, but get an error. I have included as many details as I think people would need below, but if there is anything else you need to help me, please let me know. And thanks in advance :)
-----------------------------
I run style.py with below commands. I am using 400 pictures from the celeba dataset for quick execution to test it. I earlier used the whole set (all 202k) for 5000 iterations and found I got only black images in the test-dir. I noticed style and content loss remain constant, and loss & tv loss are NaN (so huge?).

C:\Downloads2\fast-style-transfer>python style.py --checkpoint-dir ./examples/ch
eckpoints/galatea --style ./examples/style/galatea_of_the_spheres.jpg --test ./s
noopy/snoopy3.jpg --test-dir ./data/test_images --checkpoint-iterations 100 --tr
ain-path ./data/img_align_celeba_400
(1, 1280, 960, 3)
2017-10-13 21:57:06.716556: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow libr
ary wasn't compiled to use SSE instructions, but these are available on your mac
hine and could speed up CPU computations.
2017-10-13 21:57:06.716792: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow libr
ary wasn't compiled to use SSE2 instructions, but these are available on your ma
chine and could speed up CPU computations.
2017-10-13 21:57:06.717007: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow libr
ary wasn't compiled to use SSE3 instructions, but these are available on your ma
chine and could speed up CPU computations.
2017-10-13 21:57:06.717238: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow libr
ary wasn't compiled to use SSE4.1 instructions, but these are available on your
machine and could speed up CPU computations.
2017-10-13 21:57:06.717450: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow libr
ary wasn't compiled to use SSE4.2 instructions, but these are available on your
machine and could speed up CPU computations.
2017-10-13 21:57:06.717676: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow libr
ary wasn't compiled to use AVX instructions, but these are available on your mac
hine and could speed up CPU computations.
2017-10-13 21:57:06.717904: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow libr
ary wasn't compiled to use FMA instructions, but these are available on your mac
hine and could speed up CPU computations.
2017-10-13 21:57:07.468875: I c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:940] Found device 0
with properties:
name: GeForce GTX 1060 6GB
major: 6 minor: 1 memoryClockRate (GHz) 1.7085
pciBusID 0000:01:00.0
Total memory: 6.00GiB
Free memory: 5.54GiB
2017-10-13 21:57:07.469336: I c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:961] DMA: 0
2017-10-13 21:57:07.469499: I c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   Y
2017-10-13 21:57:07.469658: I c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Creating Tenso
rFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 000
0:01:00.0)
2017-10-13 21:58:09.087597: I c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Creating Tenso
rFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 000
0:01:00.0)
UID: 69
**Epoch 0, Iteration: 100, Loss: nan
style: 1.13866e+23, content:3.40418e+06, tv: nan**
2017-10-13 21:59:40.607799: I c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Creating Tenso
rFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 000
0:01:00.0)
**Epoch 1, Iteration: 100, Loss: nan
style: 1.13866e+23, content:3.40418e+06, tv: nan**
2017-10-13 22:01:14.075462: I c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Creating Tenso
rFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 000
0:01:00.0)
Training complete. For evaluation:
    `python evaluate.py --checkpoint ./examples/checkpoints/galatea ...`

So the above trained and I attempted to use evaluate.py with

C:\Downloads2\fast-style-transfer>python evaluate.py --checkpoint ./examples/che
ckpoints/galatea.ckpt --in-path ./examples/content/photo.jpg --out-path ./exampl
es/results/galatea1.jpg

I get the following error running this (it is so long it scrolls off the command console, seems to just repeat same error over and over at first):

2017-10-13 21:34:25.141903: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\framework\op_kernel.cc:1158] Data loss: Unable to ope
n table file .\examples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad
 magic number): perhaps your file is in a different file format and you need to
use a different restore operator?
2017-10-13 21:34:25.146079: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.146094: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.146752: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\framework\op_kernel.cc:1158] Data loss: Unable to ope
n table file .\examples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad
 magic number): perhaps your file is in a different file format and you need to
use a different restore operator?
2017-10-13 21:34:25.150303: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.150322: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.150639: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\framework\op_kernel.cc:1158] Data loss: Unable to ope
n table file .\examples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad
 magic number): perhaps your file is in a different file format and you need to
use a different restore operator?
2017-10-13 21:34:25.154325: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.154408: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.155042: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\framework\op_kernel.cc:1158] Data loss: Unable to ope
n table file .\examples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad
 magic number): perhaps your file is in a different file format and you need to
use a different restore operator?
2017-10-13 21:34:25.158410: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.158527: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.159095: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\framework\op_kernel.cc:1158] Data loss: Unable to ope
n table file .\examples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad
 magic number): perhaps your file is in a different file format and you need to
use a different restore operator?
2017-10-13 21:34:25.162800: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.162875: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.163172: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\framework\op_kernel.cc:1158] Data loss: Unable to ope
n table file .\examples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad
 magic number): perhaps your file is in a different file format and you need to
use a different restore operator?
2017-10-13 21:34:25.167115: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.167136: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.167779: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\framework\op_kernel.cc:1158] Data loss: Unable to ope
n table file .\examples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad
 magic number): perhaps your file is in a different file format and you need to
use a different restore operator?
2017-10-13 21:34:25.171424: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.171443: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.172112: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\framework\op_kernel.cc:1158] Data loss: Unable to ope
n table file .\examples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad
 magic number): perhaps your file is in a different file format and you need to
use a different restore operator?
2017-10-13 21:34:25.174885: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.174940: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.175570: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\framework\op_kernel.cc:1158] Data loss: Unable to ope
n table file .\examples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad
 magic number): perhaps your file is in a different file format and you need to
use a different restore operator?
2017-10-13 21:34:25.178502: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.178506: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.179240: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\framework\op_kernel.cc:1158] Data loss: Unable to ope
n table file .\examples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad
 magic number): perhaps your file is in a different file format and you need to
use a different restore operator?
2017-10-13 21:34:25.181993: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.182072: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.182420: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\framework\op_kernel.cc:1158] Data loss: Unable to ope
n table file .\examples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad
 magic number): perhaps your file is in a different file format and you need to
use a different restore operator?
2017-10-13 21:34:25.185547: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.185558: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.186337: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\framework\op_kernel.cc:1158] Data loss: Unable to ope
n table file .\examples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad
 magic number): perhaps your file is in a different file format and you need to
use a different restore operator?
2017-10-13 21:34:25.188551: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open .\exam
ples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): per
haps your file is in a different file format and you need to use a different res
tore operator?
2017-10-13 21:34:25.188902: W c:\tf_jenkins\home\workspace\release-win\m\windows
-gpu\py\36\tensorflow\core\framework\op_kernel.cc:1158] Data loss: Unable to ope
n table file .\examples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad
 magic number): perhaps your file is in a different file format and you need to
use a different restore operator?
Traceback (most recent call last):
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\client\
session.py", line 1139, in _do_call
    return fn(*args)
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\client\
session.py", line 1121, in _run_fn
    status, run_metadata)
  File "C:\Users\msm10_000\Anaconda3\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\framewo
rk\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file
 .\examples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic numbe
r): perhaps your file is in a different file format and you need to use a differ
ent restore operator?
         [[Node: save/RestoreV2_35 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:
localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_35/tensor
_names, save/RestoreV2_35/shape_and_slices)]]
         [[Node: save/RestoreV2_24/_35 = _Recv[client_terminated=false, recv_dev
ice="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica
:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_134_save/RestoreV
2_24", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]
]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evaluate.py", line 266, in <module>
    main()
  File "evaluate.py", line 253, in main
    device=opts.device)
  File "evaluate.py", line 186, in ffwd_to_img
    ffwd(paths_in, paths_out, checkpoint_dir, batch_size=1, device_t=device)
  File "evaluate.py", line 156, in ffwd
    saver.restore(sess, checkpoint_dir)
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\trainin
g\saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\client\
session.py", line 789, in run
    run_metadata_ptr)
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\client\
session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\client\
session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\client\
session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file
 .\examples\checkpoints\galatea.ckpt: Data loss: not an sstable (bad magic numbe
r): perhaps your file is in a different file format and you need to use a differ
ent restore operator?
         [[Node: save/RestoreV2_35 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:
localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_35/tensor
_names, save/RestoreV2_35/shape_and_slices)]]
         [[Node: save/RestoreV2_24/_35 = _Recv[client_terminated=false, recv_dev
ice="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica
:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_134_save/RestoreV
2_24", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]
]

Caused by op 'save/RestoreV2_35', defined at:
  File "evaluate.py", line 266, in <module>
    main()
  File "evaluate.py", line 253, in main
    device=opts.device)
  File "evaluate.py", line 186, in ffwd_to_img
    ffwd(paths_in, paths_out, checkpoint_dir, batch_size=1, device_t=device)
  File "evaluate.py", line 148, in ffwd
    saver = tf.train.Saver()
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\trainin
g\saver.py", line 1139, in __init__
    self.build()
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\trainin
g\saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\trainin
g\saver.py", line 691, in build
    restore_sequentially, reshape)
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\trainin
g\saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\trainin
g\saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\ops\gen
_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\framewo
rk\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\framewo
rk\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\msm10_000\Anaconda3\lib\site-packages\tensorflow\python\framewo
rk\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

DataLossError (see above for traceback): Unable to open table file .\examples\ch
eckpoints\galatea.ckpt: Data loss: not an sstable (bad magic number): perhaps yo
ur file is in a different file format and you need to use a different restore op
erator?
         [[Node: save/RestoreV2_35 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:
localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_35/tensor
_names, save/RestoreV2_35/shape_and_slices)]]
         [[Node: save/RestoreV2_24/_35 = _Recv[client_terminated=false, recv_dev
ice="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica
:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_134_save/RestoreV
2_24", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]
]

Could this be because I am using jpg rather than png? I managed to use evaluate.py on a jpg with the example ckpt files. There a 4 files that save in the checkpoint-dir. None of them have extension .ckpt. They one I am sure is the checkpoint to use is fns.ckpt.data-00000-of-00001. That has size 19,660kb, which I see is not quite the size of the example checkpoints (they are 19,675kb). I renamed this to galatea.ckpt and used as an argument in the evaluate.py command above.

So the 2 things I would like some help with if you can, are:

1) How to get it to train using style.py, without just giving back total black image?
2) How to use the ckpt generated to use with evaluate.py?

**Comment by msm1089** [comment]
Found a fix in an existing issue  ( #78 )  for my 2nd question.

Changed L22 in optimize.py to

saver = tf.train.Saver(write_version=tf.train.SaverDef.V1)

It generates a deprecation warning, but it creates the ckpt file correctly :)

Still looking for a fix to the black images generated by evaluate.py. When I use --slow then it works, so a clue there...
