### ISSUE TITLE
unsupported operand type(s) for -: 'JpegImageFile' and 'JpegImageFile'

### ISSUE THREAD

**Issue by JacobLee121** [lengstrom/fast-style-transfer#101]
Epoch 0, Iteration: 5800, Loss: 8.30383e+06
style: 2.7153e+06, content:5.29904e+06, tv: 289487.0
Traceback (most recent call last):
  File "style.py", line 175, in <module>
    main()
  File "style.py", line 155, in main
    for preds, losses, i, epoch in optimize(*args, **kwargs):
  File "src/optimize.py", line 105, in optimize
    X_batch[j] = get_img(img_p, (256,256,3)).astype(np.float32)
  File "src/utils.py", line 20, in get_img
    img = scipy.misc.imresize(img, img_size)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 480, in imresize
    im = toimage(arr, mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 343, in toimage
    bytedata = bytescale(data, high=high, low=low, cmin=cmin, cmax=cmax)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 94, in bytescale
    cscale = cmax - cmin
TypeError: unsupported operand type(s) for -: 'JpegImageFile' and 'JpegImageFile'

**Comment by msm1089** [comment]
Check you have Pillow installed, it looks like you are using PIL.

**Comment by JacobLee121** [comment]
hi, thanks for your response. I can import PIL successfully, and this code has iterated for about 5800 times, but suddenly bread down

**Comment by JacobLee121** [comment]
@msm1089 hi, thanks for your response. I can import PIL successfully, and this code has iterated for about 5800 times, but suddenly bread down

**Comment by JacobLee121** [comment]
this can be solved with this link:
https://github.com/lengstrom/fast-style-transfer/issues/54
