### ISSUE TITLE
IOError: could not read bytes

### ISSUE THREAD

**Issue by fanyuzeng** [lengstrom/fast-style-transfer#109]
How to deal with this problem, ask for help.
My command as follow:
  python style.py --style examples/style/la_muse.jpg \
  --checkpoint-dir checkpoint-direction\
  --test bin/building.jpg \
  --test-dir test-direction \
  --content-weight 1.5e1 \
  --checkpoint-iterations 1000 \
  --batch-size 20

**And the terminal appears the follow:**

Traceback (most recent call last):
  File "style.py", line 167, in <module>
    main()
  File "style.py", line 147, in main
    for preds, losses, i, epoch in optimize(*args, **kwargs):
  File "src/optimize.py", line 34, in optimize
    net = vgg.net(vgg_path, style_image_pre)
  File "src/vgg.py", line 26, in net
    data = scipy.io.loadmat(data_path)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.19.1-py2.7-linux-x86_64.egg/scipy/io/matlab/mio.py", line 136, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.19.1-py2.7-linux-x86_64.egg/scipy/io/matlab/mio5.py", line 292, in get_variables
    res = self.read_var_array(hdr, process)
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.19.1-py2.7-linux-x86_64.egg/scipy/io/matlab/mio5.py", line 252, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "scipy/io/matlab/mio5_utils.pyx", line 673, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.c:7578)
  File "scipy/io/matlab/mio5_utils.pyx", line 719, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.c:6884)
  File "scipy/io/matlab/mio5_utils.pyx", line 892, in scipy.io.matlab.mio5_utils.VarReader5.read_cells (scipy/io/matlab/mio5_utils.c:9493)
  File "scipy/io/matlab/mio5_utils.pyx", line 671, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix (scipy/io/matlab/mio5_utils.c:6339)
  File "scipy/io/matlab/mio5_utils.pyx", line 721, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.c:6914)
  File "scipy/io/matlab/mio5_utils.pyx", line 967, in scipy.io.matlab.mio5_utils.VarReader5.read_struct (scipy/io/matlab/mio5_utils.c:10504)
  File "scipy/io/matlab/mio5_utils.pyx", line 671, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix (scipy/io/matlab/mio5_utils.c:6339)
  File "scipy/io/matlab/mio5_utils.pyx", line 719, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.c:6884)
  File "scipy/io/matlab/mio5_utils.pyx", line 892, in scipy.io.matlab.mio5_utils.VarReader5.read_cells (scipy/io/matlab/mio5_utils.c:9493)
  File "scipy/io/matlab/mio5_utils.pyx", line 671, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix (scipy/io/matlab/mio5_utils.c:6339)
  File "scipy/io/matlab/mio5_utils.pyx", line 703, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.c:6575)
  File "scipy/io/matlab/mio5_utils.pyx", line 776, in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex (scipy/io/matlab/mio5_utils.c:8049)
  File "scipy/io/matlab/mio5_utils.pyx", line 448, in scipy.io.matlab.mio5_utils.VarReader5.read_numeric (scipy/io/matlab/mio5_utils.c:4575)
  File "scipy/io/matlab/mio5_utils.pyx", line 353, in scipy.io.matlab.mio5_utils.VarReader5.read_element (scipy/io/matlab/mio5_utils.c:4143)
  File "scipy/io/matlab/streams.pyx", line 327, in scipy.io.matlab.streams.FileStream.read_string (scipy/io/matlab/streams.c:5353)
IOError: could not read bytes

**Comment by FFY00** [comment]
`imagenet-vgg-verydeep-19.mat` is corrupted, you should redownload it.

**Comment by lengstrom** [comment]
You should read the setup instructions.
