### ISSUE TITLE
ValueError: filter must not be larger than the input: Filter: [9x9] Input: [1x1]

### ISSUE THREAD

**Issue by dmunsigned** [lengstrom/fast-style-transfer#114]
Hi Everyone, 

Any thoughts on this one. Has me stumped. 

Traceback (most recent call last):
  File "evaluate.py", line 266, in <module>
    main()
  File "evaluate.py", line 263, in main
    batch_size=opts.batch_size)
  File "evaluate.py", line 147, in ffwd
    preds = transform.net(img_placeholder)
  File "src/transform.py", line 8, in net
    conv1 = _conv_layer(image, 32, 9, 1)
  File "src/transform.py", line 25, in _conv_layer
    net = tf.nn.conv2d(net, weights_init, strides_shape, padding='SAME')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 295, in conv2d
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2156, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1612, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/common_shapes.py", line 238, in conv2d_shape
    in_rows, in_cols, filter_rows, filter_cols, stride_r, stride_c, padding)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/common_shapes.py", line 151, in get2d_conv_output_size
    % (filter_height, filter_width, input_height, input_width))
ValueError: filter must not be larger than the input: Filter: [9x9] Input: [1x1]

**Comment by lengstrom** [comment]
Did you change the code at all?
