### ISSUE TITLE
module 'tensorflow' has no attribute 'Graph'

### ISSUE THREAD

**Issue by zkl99999** [lengstrom/fast-style-transfer#125]
python3 evaluate.py --checkpoint ./Fast\ Style\ Transfer\ Models/rain_princess.ckpt --in-path ./wave.jpg --out-path ./zkl.jpg
Traceback (most recent call last):
  File "evaluate.py", line 212, in <module>
    main()
  File "evaluate.py", line 199, in main
    device=opts.device)
  File "evaluate.py", line 132, in ffwd_to_img
    ffwd(paths_in, paths_out, checkpoint_dir, batch_size=1, device_t=device)
  File "evaluate.py", line 82, in ffwd
    g = tf.Graph()
AttributeError: module 'tensorflow' has no attribute 'Graph'

**Comment by blkht-r4n** [comment]
Same problem. Any fix?

**Comment by himanshu-14** [comment]
Got module 'tensorflow' has no attribute 'Session'. Seems to be a version issue what should be done to run this project? I tried following the Readme.md versons while creating conda environment but conda cant find the old versions in the channels.
