### ISSUE TITLE
Error on quantised model

### ISSUE THREAD

**Issue by kmonachopoulos** [lengstrom/fast-style-transfer#135]
I managed to convert the .chkpt file to .pb file and currently extracting the output image from add_37:0 tensor. The results however are different from inferencing using the checkpoint file.

Wave style checkpoint out: 

 
![image](https://user-images.githubusercontent.com/3832904/35874936-bae9d4d6-0b65-11e8-8d86-86ea5cc665ea.png)

Wave style protobuf out (using add_37:0 tensor): 

![image](https://user-images.githubusercontent.com/3832904/35875103-2f564e26-0b66-11e8-81b3-1ca92e6a4465.png)

Is this tensor correct? I cannot find any other tensor after that with correct dimensions. When I finally quantize the model using `transform_graph`  like

```
--transforms='
  add_default_attributes
  strip_unused_nodes(type=float)
  remove_nodes(op=CheckNumerics)
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights
  quantize_nodes
  strip_unused_nodes
  sort_by_execution_order' 
```
and try to inference again, I get the following error : 

```
Traceback (most recent call last):
  File "Inf_Image_pb.py", line 90, in <module>
    Session_out = sess.run(l_output, feed_dict={l_input: image})            
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: input_max_range must be larger than input_min_range.
	 [[Node: mul_11_eightbit/div_11/quantize = QuantizeV2[T=DT_QUINT8, mode="MIN_FIRST", _device="/job:localhost/replica:0/task:0/device:CPU:0"](div_11, mul_11_eightbit/div_11/min, mul_11_eightbit/div_11/max)]]

Caused by op u'mul_11_eightbit/div_11/quantize', defined at:
  File "Inf_Image_pb.py", line 75, in <module>
    producer_op_list=None
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): input_max_range must be larger than input_min_range.
	 [[Node: mul_11_eightbit/div_11/quantize = QuantizeV2[T=DT_QUINT8, mode="MIN_FIRST", _device="/job:localhost/replica:0/task:0/device:CPU:0"](div_11, mul_11_eightbit/div_11/min, mul_11_eightbit/div_11/max)]]
```
I am using the pre-trained models for inference.

**Comment by zxj11838** [comment]
I would like to ask you how do you get the PB model file? Thank you

**Comment by justinrmiller** [comment]
@kmonachopoulos Were you able to make this work? I'd like to try running inference w/style transfer models  on Coral EdgeTPU devices if possible and I think your work might help with that (if it's even possible on such devices).
