### ISSUE TITLE
Can't load model file or directory

### ISSUE THREAD

**Issue by adayton1** [lengstrom/fast-style-transfer#138]
If I try to provide a specific model (i.e. wave.ckpt) I get the following ValueError:

Traceback (most recent call last):
  File "evaluate.py", line 212, in <module>
    main()
  File "evaluate.py", line 199, in main
    device=opts.device)
  File "evaluate.py", line 132, in ffwd_to_img
    ffwd(paths_in, paths_out, checkpoint_dir, batch_size=1, device_t=device)
  File "evaluate.py", line 102, in ffwd
    saver.restore(sess, checkpoint_dir)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1757, in restore
    " to the checkpoint files." % save_path)
ValueError: The specified path: ./wave.ckpt is a file. Please specify only the path prefix to the checkpoint files.

But if I just specify the directory containing the checkpoint, I get the following exception:

Traceback (most recent call last):
  File "evaluate.py", line 212, in <module>
    main()
  File "evaluate.py", line 199, in main
    device=opts.device)
  File "evaluate.py", line 132, in ffwd_to_img
    ffwd(paths_in, paths_out, checkpoint_dir, batch_size=1, device_t=device)
  File "evaluate.py", line 100, in ffwd
    raise Exception("No checkpoint found...")
Exception: No checkpoint found...

**Comment by dwangarc** [comment]
try this 
`from tensorflow.core.protobuf import saver_pb2`
  and define the 'saver' like `saver = tf.train.Saver(write_version=saver_pb2.SaverDef.V1)   `
