### ISSUE TITLE
What are the requirements exactly?

### ISSUE THREAD

**Issue by weisswurst** [lengstrom/fast-style-transfer#140]
The readme file says the requirements are:

TensorFlow 0.11.0
Python 2.7.9, Pillow 3.4.2, scipy 0.18.1, numpy 1.11.2

But they seem outdated.
I saw a few references to tensorflow 1.0.0. What are the full requirements exactly?

**Comment by Scoobadood** [comment]
It seems that ffmpeg and moviepy are both required if you want to train a new style

**Comment by marcsyp** [comment]
I can confirm the above -- and add scipy to the list.

Also, I can confirm that I was able to train a style and evaluate using TensorFlow 1.8.0 built against CUDA 9.1 (using a wheel I found on the web because my gfx card is only supported in CUDA 9.1+ but tensorflow currently is only officially built against 9.0).

Cheers,
Marc

**Comment by krupax** [comment]
I can't seem to get round the paradox of needing python 2.79 for these scripts and that there seems to be no way to install tensorflow for that version - I've got it installed in python 3.x but get this when I run style.py in 2.79

Traceback (most recent call last):
  File "style.py", line 5, in <module>
    from optimize import optimize
  File "src\optimize.py", line 3, in <module>
    import vgg, pdb, time
  File "src\vgg.py", line 3, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow

any ideas or leads anyone has will be gratefully accepted :)

Chris
