### ISSUE TITLE
bug running style.py: KeyError: 'normalization'

### ISSUE THREAD

**Issue by diramazioni** [lengstrom/fast-style-transfer#158]
I've followed the readme and have all the dependency setup (both imagenet-vgg-verydeep-19.mat & train2014 are present) but when I try to run style.py I got an error:
```
Train set has been trimmed slightly..
(1, 1409, 1024, 3)
2018-06-17 09:58:51.354098: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-06-17 09:58:51.469426: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-06-17 09:58:51.469999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 980 Ti major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:0e:00.0
totalMemory: 5.93GiB freeMemory: 5.23GiB
2018-06-17 09:58:51.470022: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-17 09:58:53.175395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-17 09:58:53.175445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-06-17 09:58:53.175454: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-06-17 09:58:53.175740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5003 MB memory) -> physical GPU (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:0e:00.0, compute capability: 5.2)
Traceback (most recent call last):
  File "style.py", line 167, in <module>
    main()
  File "style.py", line 147, in main
    for preds, losses, i, epoch in optimize(*args, **kwargs):
  File "src/optimize.py", line 34, in optimize
    net = vgg.net(vgg_path, style_image_pre)
  File "src/vgg.py", line 27, in net
    mean = data['normalization'][0][0][0]
KeyError: 'normalization'
```
any idea?

**Comment by diramazioni** [comment]
it turns out that this code is based on a different version of vgg [see here] (https://github.com/anishathalye/neural-style/issues/4) even if the file has the same name!  The correct link has moved here: http://www.vlfeat.org/matconvnet/models/beta16/imagenet-vgg-verydeep-19.mat

However I'm still **unable** to train a new style for ResourceExhaustedError even with a relatively **small** image for style 819 × 647 pixel having a GPU with 6gb memory ... this is simply ridiculous and frustrating given that running the program with already computed styles (evaluate.py) works really well  but training a new style after downloading these huge files it's impossible.
