### ISSUE TITLE
Training failed becasue of the following error at iteration 7100+

### ISSUE THREAD

**Issue by victpf** [lengstrom/fast-style-transfer#166]
Epoch 0, Iteration: 7120, Loss: 8611719.0
style: 2604105.8, content:5590211.0, tv: 417401.88
Traceback (most recent call last):
  File "style.py", line 167, in <module>
    main()
  File "style.py", line 147, in main
    for preds, losses, i, epoch in optimize(*args, **kwargs):
  File "src/optimize.py", line 105, in optimize
    X_batch[j] = get_img(img_p, (256,256,3)).astype(np.float32)
  File "src/utils.py", line 19, in get_img
    img = scipy.misc.imresize(img, img_size)
  File "/root/anaconda3/lib/python3.6/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/root/anaconda3/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 555, in imresize
    im = toimage(arr, mode=mode)
  File "/root/anaconda3/lib/python3.6/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/root/anaconda3/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 381, in toimage
    bytedata = bytescale(data, high=high, low=low, cmin=cmin, cmax=cmax)
  File "/root/anaconda3/lib/python3.6/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/root/anaconda3/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 93, in bytescale
    cmin = data.min()
  File "/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
TypeError: '<=' not supported between instances of 'JpegImageFile' and 'JpegImageFile'

**Comment by adnphllps** [comment]
I had the same issue. The problem is that some of the training images in the train2014 set were corrupted. I had to delete three files, after which the error was resolved. To find the corrupted images I ran the following command line search:

`find . -name \*.jpg -exec identify -verbose -regard-warnings {} >/dev/null "+"`

![screenshot 2018-10-26 11 44 13](https://user-images.githubusercontent.com/1544500/47580813-da077180-d91d-11e8-9bd4-18d2d787133d.png)

Just delete the files listed and the error should be resolved. You could find search for good versions of the files and replace them if you want.
