### ISSUE TITLE
More than one input image error(?)

### ISSUE THREAD

**Issue by techninja** [lengstrom/fast-style-transfer#17]
You can change the title to something more fitting if this isn't what's going on, but I get the following whenever there's more than one jpg in the given input dir, but everything works fine if there's only one.

Salient output dump, Ubuntu 16.10, 64bit:
```
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: GeForce GTX 950
major: 5 minor: 2 memoryClockRate (GHz) 1.3165
pciBusID 0000:03:00.0
Total memory: 1.95GiB
Free memory: 1.64GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950, pci bus id: 0000:03:00.0)
Traceback (most recent call last):
  File "evaluate.py", line 125, in <module>
    main()
  File "evaluate.py", line 122, in main
    batch_size=opts.batch_size)
  File "evaluate.py", line 54, in ffwd
    assert img.shape == img_shape
AssertionError

```

**Comment by lengstrom** [comment]
As noted in the [documentation](https://github.com/lengstrom/fast-style-transfer/blob/master/docs.md#evaluatepy), the script assumes that every image in the directory has the same dimensions, which might be your problem. See https://github.com/lengstrom/fast-style-transfer/pull/13, this will probably be fixed soon.
