### ISSUE TITLE
transform_video isn't cooperating with MoviePy

### ISSUE THREAD

**Issue by PPiinngg** [lengstrom/fast-style-transfer#187]
since i have an affinity for only making things worse by trying to fix them i thought i'd post this error here to see if any of you folks could help me get this working

D:\fast-style-transfer-master>python transform_video.py --checkpoint checkpoint/inkify --in-path input --out-path out --device /cpu:0
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 277, in ffmpeg_parse_infos
    line = [l for l in lines if keyword in l][index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transform_video.py", line 55, in <module>
    main()
  File "transform_video.py", line 51, in main
    evaluate.ffwd_video(opts.in_path, opts.out, opts.checkpoint, opts.device, opts.batch_size)
  File "D:\fast-style-transfer-master\evaluate.py", line 22, in ffwd_video
    video_clip = VideoFileClip(path_in, audio=False)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 33, in __init__
    fps_source)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 283, in ffmpeg_parse_infos
    filename, infos))
OSError: MoviePy error: failed to read the duration of file input.
Here are the file infos returned by ffmpeg:

ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
input: Permission denied

considering that half the errors are to do with moviepy i'd assume that this program is designed to work with an older version and the one i have installed has a few changes but that's as far as i can go into figuring out what's wrong without my brain exploding

**Comment by PPiinngg** [comment]
if it makes any difference evaluate.py works fine

**Comment by JEF1056** [comment]
All the way at the end, it states that permission was denied. Perhaps try to specify the file in the `input` folder, and write a full path?
