### ISSUE TITLE
implementing at nvidia jetson nano

### ISSUE THREAD

**Issue by AndreV84** [lengstrom/fast-style-transfer#202]
/fast-style-transfer$ python3 transform_video.py --in-path /usr/share/visionworks/sources/data/parking.avi   --checkpoint models/la_muse.ckpt   --out-path out/video.mp4   --device /gpu:0   --batch-size 4
2019-06-08 00:43:17.158582: W tensorflow/core/platform/profile_utils/cpu_utils.cc:98] Failed to find bogomips in /proc/cpuinfo; cannot determine CPU frequency
2019-06-08 00:43:17.189992: I tensorflow/compiler/xla/service/service.cc:161] XLA service 0x1dc28700 executing computations on platform Host. Devices:
2019-06-08 00:43:17.190081: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-08 00:43:17.386300: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:965] ARM64 does not support NUMA - returning NUMA node zero
2019-06-08 00:43:17.386794: I tensorflow/compiler/xla/service/service.cc:161] XLA service 0x1e23f830 executing computations on platform CUDA. Devices:
2019-06-08 00:43:17.386858: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (0): NVIDIA Tegra X1, Compute Capability 5.3
2019-06-08 00:43:17.388303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: NVIDIA Tegra X1 major: 5 minor: 3 memoryClockRate(GHz): 0.9216
pciBusID: 0000:00:00.0
totalMemory: 3.87GiB freeMemory: 1.60GiB
2019-06-08 00:43:17.388383: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-08 00:43:22.228461: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-08 00:43:22.228526: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-08 00:43:22.228548: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-08 00:43:22.228747: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 720 MB memory) -> physical GPU (device: 0, name: NVIDIA Tegra X1, pci bus id: 0000:00:00.0, compute capability: 5.3)
WARNING:tensorflow:From /home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-06-08 00:43:35.116000: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.11GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-06-08 00:43:37.445473: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 337.50MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-06-08 00:43:39.899343: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 337.50MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-06-08 00:43:40.312784: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 677.25MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-06-08 00:43:57.892513: W tensorflow/core/common_runtime/bfc_allocator.cc:267] Allocator (GPU_0_bfc) ran out of memory trying to allocate 150.00MiB.  Current allocation summary follows.
2019-06-08 00:43:57.892898: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (256): 	Total Chunks: 13, Chunks in use: 13. 3.2KiB allocated for chunks. 3.2KiB in use in bin. 1.5KiB client-requested in use in bin.
2019-06-08 00:43:57.893138: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (512): 	Total Chunks: 22, Chunks in use: 22. 11.0KiB allocated for chunks. 11.0KiB in use in bin. 11.0KiB client-requested in use in bin.
2019-06-08 00:43:57.893259: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (1024): 	Total Chunks: 1, Chunks in use: 1. 1.2KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
2019-06-08 00:43:57.893363: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (2048): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-06-08 00:43:57.893527: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (4096): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-06-08 00:43:57.893647: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (8192): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-06-08 00:43:57.893754: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (16384): 	Total Chunks: 2, Chunks in use: 2. 61.0KiB allocated for chunks. 61.0KiB in use in bin. 60.8KiB client-requested in use in bin.
2019-06-08 00:43:57.893859: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (32768): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-06-08 00:43:57.893959: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (65536): 	Total Chunks: 3, Chunks in use: 3. 216.0KiB allocated for chunks. 216.0KiB in use in bin. 216.0KiB client-requested in use in bin.
2019-06-08 00:43:57.894061: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (131072): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-06-08 00:43:57.894175: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (262144): 	Total Chunks: 2, Chunks in use: 2. 576.0KiB allocated for chunks. 576.0KiB in use in bin. 576.0KiB client-requested in use in bin.
2019-06-08 00:43:57.894271: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (524288): 	Total Chunks: 10, Chunks in use: 10. 6.29MiB allocated for chunks. 6.29MiB in use in bin. 5.62MiB client-requested in use in bin.
2019-06-08 00:43:57.894370: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (1048576): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-06-08 00:43:57.894455: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (2097152): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-06-08 00:43:57.894557: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (4194304): 	Total Chunks: 1, Chunks in use: 0. 7.86MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-06-08 00:43:57.894658: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (8388608): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-06-08 00:43:57.894750: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (16777216): 	Total Chunks: 1, Chunks in use: 0. 16.00MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-06-08 00:43:57.894856: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (33554432): 	Total Chunks: 1, Chunks in use: 0. 32.00MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-06-08 00:43:57.894953: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (67108864): 	Total Chunks: 1, Chunks in use: 1. 75.00MiB allocated for chunks. 75.00MiB in use in bin. 75.00MiB client-requested in use in bin.
2019-06-08 00:43:57.895133: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (134217728): 	Total Chunks: 1, Chunks in use: 1. 181.00MiB allocated for chunks. 181.00MiB in use in bin. 150.00MiB client-requested in use in bin.
2019-06-08 00:43:57.895350: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (268435456): 	Total Chunks: 1, Chunks in use: 1. 256.00MiB allocated for chunks. 256.00MiB in use in bin. 150.55MiB client-requested in use in bin.
2019-06-08 00:43:57.895445: I tensorflow/core/common_runtime/bfc_allocator.cc:613] Bin for 150.00MiB was 128.00MiB, Chunk State: 
2019-06-08 00:43:57.895507: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00850000 of size 1280
2019-06-08 00:43:57.895557: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00850500 of size 31232
2019-06-08 00:43:57.895600: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00857f00 of size 512
2019-06-08 00:43:57.895644: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00858100 of size 512
2019-06-08 00:43:57.895689: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00858300 of size 1015040
2019-06-08 00:43:57.895779: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00950000 of size 256
2019-06-08 00:43:57.895838: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00950100 of size 512
2019-06-08 00:43:57.895901: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00950300 of size 512
2019-06-08 00:43:57.895962: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00950500 of size 589824
2019-06-08 00:43:57.896020: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf009e0500 of size 589824
2019-06-08 00:43:57.896078: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00a70500 of size 512
2019-06-08 00:43:57.896136: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00a70700 of size 512
2019-06-08 00:43:57.896195: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00a70900 of size 256
2019-06-08 00:43:57.896257: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00a70a00 of size 512
2019-06-08 00:43:57.896323: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00a70c00 of size 512
2019-06-08 00:43:57.896395: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00a70e00 of size 294912
2019-06-08 00:43:57.896472: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00ab8e00 of size 619008
2019-06-08 00:43:57.896549: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00b50000 of size 256
2019-06-08 00:43:57.896626: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00b50100 of size 256
2019-06-08 00:43:57.896706: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00b50200 of size 512
2019-06-08 00:43:57.896789: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00b50400 of size 256
2019-06-08 00:43:57.896870: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00b50500 of size 31232
2019-06-08 00:43:57.896960: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00b57f00 of size 512
2019-06-08 00:43:57.897043: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00b58100 of size 589824
2019-06-08 00:43:57.897117: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00be8100 of size 589824
2019-06-08 00:43:57.897190: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00c78100 of size 256
2019-06-08 00:43:57.897265: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00c78200 of size 256
2019-06-08 00:43:57.897358: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00c78300 of size 73728
2019-06-08 00:43:57.897545: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00c8a300 of size 256
2019-06-08 00:43:57.897647: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00c8a400 of size 512
2019-06-08 00:43:57.897732: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00c8a600 of size 256
2019-06-08 00:43:57.897873: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00c8a700 of size 256
2019-06-08 00:43:57.898047: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00c8a800 of size 512
2019-06-08 00:43:57.898182: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00c8aa00 of size 294912
2019-06-08 00:43:57.898293: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00cd2a00 of size 512
2019-06-08 00:43:57.898406: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00cd2c00 of size 512
2019-06-08 00:43:57.898602: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00cd2e00 of size 589824
2019-06-08 00:43:57.898717: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00d62e00 of size 512
2019-06-08 00:43:57.898854: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00d63000 of size 512
2019-06-08 00:43:57.898966: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00d63200 of size 512
2019-06-08 00:43:57.899075: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00d63400 of size 512
2019-06-08 00:43:57.899187: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00d63600 of size 589824
2019-06-08 00:43:57.899453: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00df3600 of size 589824
2019-06-08 00:43:57.899604: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00e83600 of size 512
2019-06-08 00:43:57.899669: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00e83800 of size 512
2019-06-08 00:43:57.899719: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00e83a00 of size 512
2019-06-08 00:43:57.899779: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00e83c00 of size 512
2019-06-08 00:43:57.899827: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00e83e00 of size 836096
2019-06-08 00:43:57.899874: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00f50000 of size 73728
2019-06-08 00:43:57.899958: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00f62000 of size 256
2019-06-08 00:43:57.900003: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00f62100 of size 256
2019-06-08 00:43:57.900047: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00f62200 of size 256
2019-06-08 00:43:57.900179: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf00f62300 of size 73728
2019-06-08 00:43:57.900276: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Free  at 0xf00f74300 of size 8240384
2019-06-08 00:43:57.900331: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Free  at 0xf01750000 of size 16777216
2019-06-08 00:43:57.900407: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Free  at 0xf02750000 of size 33554432
2019-06-08 00:43:57.900478: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf04750000 of size 78643200
2019-06-08 00:43:57.900561: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf09250000 of size 189792256
2019-06-08 00:43:57.900619: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0xf14b70000 of size 268435456
2019-06-08 00:43:57.900683: I tensorflow/core/common_runtime/bfc_allocator.cc:638]      Summary of in-use Chunks by size: 
2019-06-08 00:43:57.900779: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 13 Chunks of size 256 totalling 3.2KiB
2019-06-08 00:43:57.900878: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 22 Chunks of size 512 totalling 11.0KiB
2019-06-08 00:43:57.900943: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 1280 totalling 1.2KiB
2019-06-08 00:43:57.901023: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 2 Chunks of size 31232 totalling 61.0KiB
2019-06-08 00:43:57.901104: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 3 Chunks of size 73728 totalling 216.0KiB
2019-06-08 00:43:57.901141: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 2 Chunks of size 294912 totalling 576.0KiB
2019-06-08 00:43:57.901168: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 7 Chunks of size 589824 totalling 3.94MiB
2019-06-08 00:43:57.901195: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 619008 totalling 604.5KiB
2019-06-08 00:43:57.901217: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 836096 totalling 816.5KiB
2019-06-08 00:43:57.901238: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 1015040 totalling 991.2KiB
2019-06-08 00:43:57.901263: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 78643200 totalling 75.00MiB
2019-06-08 00:43:57.901288: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 189792256 totalling 181.00MiB
2019-06-08 00:43:57.901308: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 268435456 totalling 256.00MiB
2019-06-08 00:43:57.901328: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Sum Total of in-use chunks: 519.14MiB
2019-06-08 00:43:57.901363: I tensorflow/core/common_runtime/bfc_allocator.cc:647] Stats: 
Limit:                   755863552
InUse:                   544359168
MaxInUse:                561136384
NumAllocs:                     184
MaxAllocSize:            268435456

2019-06-08 00:43:57.901399: W tensorflow/core/common_runtime/bfc_allocator.cc:271] **________*****************************************xxxx***************************xxxxxxxxxxxxxxxxxx
2019-06-08 00:43:57.901462: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at conv_grad_input_ops.cc:1069 : Resource exhausted: OOM when allocating tensor with shape[4,32,480,640] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[4,32,480,640] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node conv2d_transpose_1}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[{{node add_37}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transform_video.py", line 55, in <module>
    main()
  File "transform_video.py", line 51, in main
    evaluate.ffwd_video(opts.in_path, opts.out, opts.checkpoint, opts.device, opts.batch_size)
  File "/home/jetbot/fast-style-transfer/evaluate.py", line 62, in ffwd_video
    style_and_write(frame_count)
  File "/home/jetbot/fast-style-transfer/evaluate.py", line 53, in style_and_write
    _preds = sess.run(preds, feed_dict={img_placeholder: X})
  File "/home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[4,32,480,640] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node conv2d_transpose_1 (defined at src/transform.py:41) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[node add_37 (defined at src/transform.py:17) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'conv2d_transpose_1', defined at:
  File "transform_video.py", line 55, in <module>
    main()
  File "transform_video.py", line 51, in main
    evaluate.ffwd_video(opts.in_path, opts.out, opts.checkpoint, opts.device, opts.batch_size)
  File "/home/jetbot/fast-style-transfer/evaluate.py", line 37, in ffwd_video
    preds = transform.net(img_placeholder)
  File "src/transform.py", line 15, in net
    conv_t2 = _conv_tranpose_layer(conv_t1, 32, 3, 2)
  File "src/transform.py", line 41, in _conv_tranpose_layer
    net = tf.nn.conv2d_transpose(net, weights_init, tf_shape, strides_shape, padding='SAME')
  File "/home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1654, in conv2d_transpose
    name=name)
  File "/home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1307, in conv2d_backprop_input
    name=name)
  File "/home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[4,32,480,640] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node conv2d_transpose_1 (defined at src/transform.py:41) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[node add_37 (defined at src/transform.py:17) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by AndreV84** [comment]
` python3 transform_video.py --in-path /usr/share/visionworks/sources/data/parking.avi   --checkpoint models/la_muse.ckpt   --out-path out/video.mp4   --device /gpu:0   --batch-size 1
2019-06-08 00:50:35.703360: W tensorflow/core/platform/profile_utils/cpu_utils.cc:98] Failed to find bogomips in /proc/cpuinfo; cannot determine CPU frequency
2019-06-08 00:50:35.704557: I tensorflow/compiler/xla/service/service.cc:161] XLA service 0x2f323700 executing computations on platform Host. Devices:
2019-06-08 00:50:35.704811: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-08 00:50:35.841787: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:965] ARM64 does not support NUMA - returning NUMA node zero
2019-06-08 00:50:35.842078: I tensorflow/compiler/xla/service/service.cc:161] XLA service 0x2f93a830 executing computations on platform CUDA. Devices:
2019-06-08 00:50:35.842132: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (0): NVIDIA Tegra X1, Compute Capability 5.3
2019-06-08 00:50:35.845334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: NVIDIA Tegra X1 major: 5 minor: 3 memoryClockRate(GHz): 0.9216
pciBusID: 0000:00:00.0
totalMemory: 3.87GiB freeMemory: 1.50GiB
2019-06-08 00:50:35.845413: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-08 00:50:40.448999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-08 00:50:40.449083: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-08 00:50:40.449139: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-08 00:50:40.449343: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 689 MB memory) -> physical GPU (device: 0, name: NVIDIA Tegra X1, pci bus id: 0000:00:00.0, compute capability: 5.3)
WARNING:tensorflow:From /home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.

`

**Comment by AndreV84** [comment]
` python3 transform_video.py --in-path /usr/share/visionworks/sources/data/signs.avi --checkpoint models/wreck.ckpt  --out-path out/video.mp4  --device /gpu:0  --batch-size 0
2019-06-08 02:21:02.072955: W tensorflow/core/platform/profile_utils/cpu_utils.cc:98] Failed to find bogomips in /proc/cpuinfo; cannot determine CPU frequency
2019-06-08 02:21:02.078081: I tensorflow/compiler/xla/service/service.cc:161] XLA service 0x27beee10 executing computations on platform Host. Devices:
2019-06-08 02:21:02.078173: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-08 02:21:02.223736: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:965] ARM64 does not support NUMA - returning NUMA node zero
2019-06-08 02:21:02.224073: I tensorflow/compiler/xla/service/service.cc:161] XLA service 0x282f8490 executing computations on platform CUDA. Devices:
2019-06-08 02:21:02.224129: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (0): NVIDIA Tegra X1, Compute Capability 5.3
2019-06-08 02:21:02.224478: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: NVIDIA Tegra X1 major: 5 minor: 3 memoryClockRate(GHz): 0.9216
pciBusID: 0000:00:00.0
totalMemory: 3.87GiB freeMemory: 133.02MiB
2019-06-08 02:21:02.224531: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-08 02:21:10.929165: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-08 02:21:10.992058: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-08 02:21:10.992285: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-08 02:21:11.029218: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 107 MB memory) -> physical GPU (device: 0, name: NVIDIA Tegra X1, pci bus id: 0000:00:00.0, compute capability: 5.3)
WARNING:tensorflow:From /home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/jetbot/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "transform_video.py", line 55, in <module>
    main()
  File "transform_video.py", line 51, in main
    evaluate.ffwd_video(opts.in_path, opts.out, opts.checkpoint, opts.device, opts.batch_size)
  File "/home/jetbot/fast-style-transfer/evaluate.py", line 59, in ffwd_video
    X[frame_count] = frame
IndexError: index 0 is out of bounds for axis 0 with size 0
`
