### ISSUE TITLE
More models?

### ISSUE THREAD

**Issue by mal4k** [lengstrom/fast-style-transfer#212]
Not an issue but is there any place where I can find more pre-trained models for style transfer? Also is there a platform where I can publish custom trained models?

Thanks

**Comment by justinrmiller** [comment]
A model clearinghouse would be interesting. I have a few I could contribute, let me see if I can get them uploaded somewhere.

**Comment by Zorrat** [comment]
> A model clearinghouse would be interesting. I have a few I could contribute, let me see if I can get them uploaded somewhere.

Id love to take a look at some of those!

**Comment by a-3isa** [comment]
hi can any one help me with the evaluate code i have this error

`2022-06-21 17:16:10.533518: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Processing images of shape 474x712x3
Traceback (most recent call last):
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 558, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 558, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\util\compat.py", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got 9

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evaluate.py", line 211, in <module>
    main()
  File "evaluate.py", line 205, in main
    device_t=opts.device, batch_size=opts.batch_size)
  File "evaluate.py", line 146, in ffwd_different_dimensions
    checkpoint_dir, device_t, batch_size)
  File "evaluate.py", line 92, in ffwd
    preds = transform.net(img_placeholder)
  File "src\transform.py", line 6, in net
    conv1 = _conv_layer(image, 32, 9, 1)
  File "src\transform.py", line 21, in _conv_layer
    weights_init = _conv_init_vars(net, num_filters, filter_size)
  File "src\transform.py", line 66, in _conv_init_vars
    weights_init = tf.Variable(tf.random.truncated_normal(weights_shape, stddev=WEIGHTS_INIT_STDEV, seed=1), dtype=tf.float32)
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\random_ops.py", line 173, in truncated_normal
    shape_tensor = _ShapeTensor(shape)
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\random_ops.py", line 44, in _ShapeTensor
    return ops.convert_to_tensor(shape, dtype=dtype, name="shape")
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\ops.py", line 1039, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\ops.py", line 1097, in convert_to_tensor_v2
    as_ref=False)
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\constant_op.py", line 304, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\constant_op.py", line 245, in constant
    allow_broadcast=True)
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\constant_op.py", line 283, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 562, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [9, 9, Dimension(3), 32]. Consider casting elements to a supported type.`
