### ISSUE TITLE
ffmpeg_writer issue invalid argument

### ISSUE THREAD

**Issue by rmasiso** [lengstrom/fast-style-transfer#245]
this is the command I'm running:
```
python transform_video.py --in-path B:\Projects\AI\styletransfer\fast-style-transfer-master\inputs\joey3.mp4 \
  --checkpoint B:\Projects\AI\styletransfer\fast-style-transfer-master\pretrained_models\scream.ckpt \
  --out-path video1.mp4 \
  --device /gpu:0 \
  --batch-size 1
```

these are the installed libraries from `conda list`
```
(tf-gpu) C:\WINDOWS\system32>conda list
# packages in environment at C:\Users\rolo\Anaconda3\envs\tf-gpu:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu
absl-py                   0.9.0                    py37_0
astor                     0.8.0                    py37_0
attrs                     19.3.0                     py_0
backcall                  0.1.0                    py37_0
blas                      1.0                         mkl
bleach                    3.1.4                      py_0
blinker                   1.4                      py37_0
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cachetools                3.1.1                      py_0
certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
click                     7.1.2                      py_0
colorama                  0.4.3                      py_0
cryptography              2.9.2            py37h7a1dbc1_0
cudatoolkit               10.1.243             h74a9793_0
cudnn                     7.6.5                cuda10.1_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
entrypoints               0.3                      py37_0
ffmpeg                    4.2.3                ha925a31_0    conda-forge
gast                      0.2.2                    py37_0
git                       2.23.0               h6bb4b03_0    anaconda
google-auth               1.14.1                     py_0
google-auth-oauthlib      0.4.1                      py_2
google-pasta              0.2.0                      py_0
grpcio                    1.27.2           py37h351948d_0
h5py                      2.10.0           py37h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.9                        py_1
imageio                   2.8.0                    pypi_0    pypi
imageio-ffmpeg            0.4.2                    pypi_0    pypi
importlib-metadata        1.6.0                    py37_0
importlib_metadata        1.6.0                         0
intel-openmp              2020.1                      216
ipykernel                 5.1.4            py37h39e3cac_0
ipython                   7.13.0           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
jedi                      0.17.0                   py37_0
jinja2                    2.11.2                     py_0
json5                     0.9.4                      py_0
jsonschema                3.2.0                    py37_0
jupyter_client            6.1.3                      py_0
jupyter_core              4.6.3                    py37_0
jupyterlab                1.2.6              pyhf63ae98_0
jupyterlab_server         1.1.4                      py_0
keras-applications        1.0.8                      py_0
keras-preprocessing       1.1.0                      py_1
libprotobuf               3.11.4               h7bd577a_0
libsodium                 1.0.16               h9d3ae62_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.1.1                    py37_0
markupsafe                1.1.1            py37he774522_0
mistune                   0.8.4            py37he774522_0
mkl                       2020.1                      216
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.1            py37h47e9c7a_0
moviepy                   1.0.2                    pypi_0    pypi
msys2-conda-epoch         20160418                      1
nbconvert                 5.6.1                    py37_0
nbformat                  5.0.6                      py_0
notebook                  6.0.3                    py37_0
numpy                     1.18.1           py37h93ca92e_0
numpy-base                1.18.1           py37hc3f5095_1
oauthlib                  3.1.0                      py_0
openssl                   1.1.1g               he774522_0    conda-forge
opt_einsum                3.1.0                      py_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parso                     0.7.0                      py_0
pickleshare               0.7.5                    py37_0
pillow                    7.1.2                    pypi_0    pypi
pip                       20.0.2                   py37_3
proglog                   0.1.9                    pypi_0    pypi
prometheus_client         0.7.1                      py_0
prompt-toolkit            3.0.5                      py_0
prompt_toolkit            3.0.5                         0
protobuf                  3.11.4           py37h33f27b4_0
pyasn1                    0.4.8                      py_0
pyasn1-modules            0.2.7                      py_0
pycparser                 2.20                       py_0
pygments                  2.6.1                      py_0
pyjwt                     1.7.1                    py37_0
pyopenssl                 19.1.0                   py37_0
pyreadline                2.1                      py37_1
pyrsistent                0.16.0           py37he774522_0
pysocks                   1.7.1                    py37_0
python                    3.7.7                h81c818b_4
python-dateutil           2.8.1                      py_0
python_abi                3.7                     1_cp37m    conda-forge
pywin32                   227              py37he774522_1
pywinpty                  0.5.7                    py37_0
pyzmq                     18.1.1           py37ha925a31_0
requests                  2.23.0                   py37_0
requests-oauthlib         1.3.0                      py_0
rsa                       4.0                        py_0
scipy                     1.4.1            py37h9439919_0
send2trash                1.5.0                    py37_0
setuptools                47.1.1                   py37_0
six                       1.14.0                   py37_0
sqlite                    3.31.1               h2a8f88b_1
tensorboard               2.1.1                      py_1    conda-forge
tensorboard-plugin-wit    1.6.0                      py_0
tensorflow                2.1.0           gpu_py37h7db9008_0
tensorflow-base           2.1.0           gpu_py37h55f5790_0
tensorflow-estimator      2.1.0              pyhd54b08b_0
tensorflow-gpu            2.1.0                h0d30ee6_0
termcolor                 1.1.0                    py37_1
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
tornado                   6.0.4            py37he774522_1
tqdm                      4.46.1                   pypi_0    pypi
traitlets                 4.3.3                    py37_0
transform                 0.0.1                    pypi_0    pypi
urllib3                   1.25.8                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_2
wcwidth                   0.1.9                      py_0
webencodings              0.5.1                    py37_1
werkzeug                  0.16.1                     py_0
wheel                     0.34.2                   py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.12.1           py37he774522_1
zeromq                    4.3.1                h33f27b4_3
zipp                      3.1.0                      py_0
zlib                      1.2.11               h62dcd97_4
```
this is the error i get:
```Traceback (most recent call last):
  File "C:\Users\rolo\Anaconda3\envs\tf-gpu\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 136, in write_frame
    self.proc.stdin.write(img_array.tobytes())
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transform_video.py", line 55, in <module>
    main()
  File "transform_video.py", line 51, in main
    evaluate.ffwd_video(opts.in_path, opts.out, opts.checkpoint, opts.device, opts.batch_size)
  File "B:\Projects\AI\styletransfer\fast-style-transfer-master\evaluate.py", line 66, in ffwd_video
    style_and_write(frame_count)
  File "B:\Projects\AI\styletransfer\fast-style-transfer-master\evaluate.py", line 59, in style_and_write
    video_writer.write_frame(np.clip(_preds[i], 0, 255).astype(np.uint8))
  File "C:\Users\rolo\Anaconda3\envs\tf-gpu\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 180, in write_frame
    raise IOError(error)
OSError: [Errno 22] Invalid argument

MoviePy error: FFMPEG encountered the following error while writing file video1.mp4:

 b''```

I've tried everything. different versions of tensorflow, tried using python 2.7, can't get this to work!

I appreciate the help in advance!

(unfortunately, for some reason the gpu isn't recognized either, but that's a separate issue)

**Comment by lengstrom** [comment]
unfortunately have never run this on windows so I can't help ya!

**Comment by rmasiso** [comment]
Ok-- round 2, on Macbook Pro 2019 (2.3 GHz 8-Core Intel Core i9)

```
(tf-gpu) rmasis@x86_64-apple-darwin13 fast-style-transfer % conda list
# packages in environment at /Users/rmasis/opt/anaconda3/envs/tf-gpu:
#
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                       mkl  
absl-py                   0.9.0                    py37_0  
appnope                   0.1.0                    py37_0  
astor                     0.8.0                    py37_0  
attrs                     19.3.0                     py_0  
backcall                  0.1.0                    py37_0  
blas                      1.0                         mkl  
bleach                    3.1.4                      py_0  
bzip2                     1.0.8                h1de35cc_0  
c-ares                    1.15.0            h1de35cc_1001  
ca-certificates           2020.1.1                      0  
certifi                   2020.4.5.1               py37_0  
cffi                      1.14.0           py37hc512035_1  
chardet                   3.0.4                 py37_1003  
cryptography              2.9.2            py37ha12b0ac_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py37_0  
ffmpeg                    4.2.2                h97e5cf8_0  
freetype                  2.9.1                hb4e5f40_0  
gast                      0.2.2                    py37_0  
gettext                   0.19.8.1             hb0f4f8b_2  
gmp                       6.1.2                hb37e062_1  
gnutls                    3.6.5             h91ad68e_1002  
google-pasta              0.2.0                      py_0  
grpcio                    1.16.1           py37h044775b_1  
h5py                      2.10.0           py37h3134771_0  
hdf5                      1.10.4               hfa1e0ec_0  
idna                      2.9                        py_1  
imageio                   2.8.0                    pypi_0    pypi
imageio-ffmpeg            0.4.2                    pypi_0    pypi
importlib-metadata        1.6.0                    py37_0  
importlib_metadata        1.6.0                         0  
intel-openmp              2019.4                      233  
ipykernel                 5.1.4            py37h39e3cac_0  
ipython                   7.13.0           py37h5ca1d4c_0  
ipython_genutils          0.2.0                    py37_0  
jedi                      0.17.0                   py37_0  
jinja2                    2.11.2                     py_0  
jpeg                      9b                   he5867d9_2  
json5                     0.9.4                      py_0  
jsonschema                3.2.0                    py37_0  
jupyter_client            6.1.3                      py_0  
jupyter_core              4.6.3                    py37_0  
jupyterlab                1.2.6              pyhf63ae98_0  
jupyterlab_server         1.1.4                      py_0  
keras-applications        1.0.8                      py_0  
keras-preprocessing       1.1.0                      py_1  
lame                      3.100                h1de35cc_0  
libcxx                    10.0.0                        1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.3                  h0a44026_1  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.16                 h1de35cc_0  
libopus                   1.3.1                h1de35cc_0  
libpng                    1.6.37               ha441bb4_0  
libprotobuf               3.11.4               hd9629dc_0  
libsodium                 1.0.16               h3efe00b_0  
libtiff                   4.1.0                hcb84e12_1  
libvpx                    1.7.0                h378b8a2_0  
lz4-c                     1.9.2                h0a44026_0  
markdown                  3.1.1                    py37_0  
markupsafe                1.1.1            py37h1de35cc_0  
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.4                      233  
mkl-service               2.3.0            py37hfbe908c_0  
mkl_fft                   1.0.15           py37h5e564d8_0  
mkl_random                1.1.1            py37h959d312_0  
moviepy                   1.0.2                    pypi_0    pypi
nbconvert                 5.6.1                    py37_0  
nbformat                  5.0.6                      py_0  
ncurses                   6.2                  h0a44026_1  
nettle                    3.4.1                h3018a27_0  
notebook                  6.0.3                    py37_0  
numpy                     1.18.1           py37h7241aed_0  
numpy-base                1.18.1           py37h3304bdc_1  
olefile                   0.46                     py37_0  
openh264                  2.1.0                hd9629dc_0  
openssl                   1.1.1g               h1de35cc_0  
opt_einsum                3.1.0                      py_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.7.0                      py_0  
pexpect                   4.8.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    7.1.2            py37h4655f20_0  
pip                       20.0.2                   py37_3  
proglog                   0.1.9                    pypi_0    pypi
prometheus_client         0.7.1                      py_0  
prompt-toolkit            3.0.5                      py_0  
prompt_toolkit            3.0.5                         0  
protobuf                  3.11.4           py37h0a44026_0  
ptyprocess                0.6.0                    py37_0  
pycparser                 2.20                       py_0  
pygments                  2.6.1                      py_0  
pyopenssl                 19.1.0                   py37_0  
pyrsistent                0.16.0           py37h1de35cc_0  
pysocks                   1.7.1                    py37_0  
python                    3.7.7                hf48f09d_4  
python-dateutil           2.8.1                      py_0  
pyzmq                     18.1.1           py37h0a44026_0  
readline                  8.0                  h1de35cc_0  
requests                  2.23.0                   py37_0  
scipy                     1.4.1            py37h9fa6033_0  
send2trash                1.5.0                    py37_0  
setuptools                47.1.1                   py37_0  
six                       1.15.0                     py_0  
sqlite                    3.31.1               h5c1f38d_1  
tensorboard               2.0.0              pyhb38c66f_1  
tensorflow                2.0.0           mkl_py37hda344b4_0  
tensorflow-base           2.0.0           mkl_py37h66b1bf0_0  
tensorflow-estimator      2.0.0              pyh2649769_0  
termcolor                 1.1.0                    py37_1  
terminado                 0.8.3                    py37_0  
testpath                  0.4.4                      py_0  
tk                        8.6.8                ha441bb4_0  
tornado                   6.0.4            py37h1de35cc_1  
tqdm                      4.46.1                   pypi_0    pypi
traitlets                 4.3.3                    py37_0  
urllib3                   1.25.9                   pypi_0    pypi
wcwidth                   0.1.9                      py_0  
webencodings              0.5.1                    py37_1  
werkzeug                  1.0.1                      py_0  
wheel                     0.34.2                   py37_0  
wrapt                     1.12.1           py37h1de35cc_1  
x264                      1!157.20191217       h1de35cc_0  
xz                        5.2.5                h1de35cc_0  
zeromq                    4.3.1                h0a44026_3  
zipp                      3.1.0                      py_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.4.4                h1990bb4_3  
```

this is what I'm running:
```
!python transform_video.py --in-path jesus.mp4 \
  --checkpoint /Users/rmasis/Documents/Kondo_PROJECTS/Kondo_ai/fast-style-transfer/pretrained/scream.ckpt \
  --out-path video.mp4 \
  --device /gpu:0 \
  --batch-size 2
```

This is the error (the same one!)
```
Traceback (most recent call last):
  File "/Users/rmasis/opt/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_writer.py", line 136, in write_frame
    self.proc.stdin.write(img_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transform_video.py", line 55, in <module>
    main()
  File "transform_video.py", line 51, in main
    evaluate.ffwd_video(opts.in_path, opts.out, opts.checkpoint, opts.device, opts.batch_size)
  File "/Users/rmasis/Documents/Kondo_PROJECTS/Kondo_ai/fast-style-transfer/evaluate.py", line 62, in ffwd_video
    style_and_write(frame_count)
  File "/Users/rmasis/Documents/Kondo_PROJECTS/Kondo_ai/fast-style-transfer/evaluate.py", line 55, in style_and_write
    video_writer.write_frame(np.clip(_preds[i], 0, 255).astype(np.uint8))
  File "/Users/rmasis/opt/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_writer.py", line 180, in write_frame
    raise IOError(error)
OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file video.mp4:

 b''
```

**Comment by JaeDukSeo** [comment]
haha this should not be closed still getting this error
