### ISSUE TITLE
MoviePy error ,FFMPEG error,Broken pipe

### ISSUE THREAD

**Issue by tom99763** [lengstrom/fast-style-transfer#253]
I use trainsform_video and the code shows this error:
'''
OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file ./examples/results/foxy.mp4:

 b''
'''
I search for this problem for very long time and didn't find any issue about this(most of this issue is about 'permission denied' or "Unrecognized option 'preset'.\nError splitting the argument list: Option not found\n")

I tried 'conda install -c conda-forge ffmpeg' but it still shows this error.

Did someone sucesss to fix this problem?

**Comment by Fonserbc** [comment]
Same error here:

`Traceback (most recent call last):
  File "[myinstallpath]\tf-gpu\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 136, in write_frame
    self.proc.stdin.write(img_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transform_video.py", line 55, in <module>
    main()
  File "transform_video.py", line 51, in main
    evaluate.ffwd_video(opts.in_path, opts.out, opts.checkpoint, opts.device, opts.batch_size)
  File "C:\repos\fast-style-transfer\evaluate.py", line 62, in ffwd_video
    style_and_write(frame_count)
  File "C:\repos\fast-style-transfer\evaluate.py", line 55, in style_and_write
    video_writer.write_frame(np.clip(_preds[i], 0, 255).astype(np.uint8))
  File "C:\Users\fonse\anaconda3\envs\tf-gpu\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 180, in write_frame
    raise IOError(error)
OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file out/guitar/fox.mp4:

 b''`

**Comment by PGG-DeepAI** [comment]
Same error here:

`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 133, in write_frame
    self.proc.stdin.write(img_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transform_video.py", line 55, in <module>
    main()
  File "transform_video.py", line 51, in main
    evaluate.ffwd_video(opts.in_path, opts.out, opts.checkpoint, opts.device, opts.batch_size)
  File "C:\Users\P_G\IA_Transferencia_Neural_Estilos\evaluate.py", line 62, in ffwd_video
    style_and_write(frame_count)
  File "C:\Users\P_G\IA_Transferencia_Neural_Estilos\evaluate.py", line 55, in style_and_write
    video_writer.write_frame(np.clip(_preds[i], 0, 255).astype(np.uint8))
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 177, in write_frame
    raise IOError(error)
OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file video/iavid_wave1.mp4:

 b''`

I think it has to do with imageio, moviepy and ffmpeg versions (OOM is discarded as I created a 20 secs, 3kb .mp4 video and error still shows up (nvidia-smi dmon showed a maximum of 2% mem usage))

-imageio version: 2.9.0
-ffmpeg version: 4.2.2
-moviepy version:  1.0.1
-imageio-ffmpeg version: 0.4.2
-tqdm version: 4.48.2

**Comment by PGG-DeepAI** [comment]
In your activated enviroment:
"conda install moviepy" gets version 1.0.1
"pip install moviepy" gets version 1.0.2 BUT enviroment doesnt detect movie py is installed

conda installs the package here:

C:\ProgramData\Anaconda3\pkgs\moviepy-1.0.1-py_0\site-packages


pip installs the package here:

C:\ProgramData\Anaconda3\envs\tf_gpu\Lib\site-packages (replace tf_gpu for your enviroment name)

To solve this:

if you make "pip install moviepy==1.0.2" outside enviroment,
"pip show moviepy" will give you 1.0.2 version and DEFAULT location in: C:\ProgramData\Anaconda3\Lib\site-packages

if you make "conda search moviepy" it will tell you it didnt found it!

SO TO SOLVE this we need moviepy 1.0.2 installed, and not use conda install!

**Comment by novichiv** [comment]
Workaround: downgrading imageio-ffmpeg version from 0.4.3 to 0.2.0 resolves this issue.

**Comment by HilariousBojack** [comment]
> Workaround: downgrading imageio-ffmpeg version from 0.4.3 to 0.2.0 resolves this issue.

Thanks!

**Comment by nagisakuya** [comment]
I found that version of ffmpeg also cause this error. Make sure that version of ffmpeg is 3.x.

**Comment by Hotpottttt** [comment]
> Workaround: downgrading imageio-ffmpeg version from 0.4.3 to 0.2.0 resolves this issue.

why do I still got the same error after downgrading? I got almost mad

**Comment by paradiseforgithub** [comment]
已收到您的邮件,如有问题会尽快给您回复.
