### ISSUE TITLE
Checkpoint file nowhere to be found

### ISSUE THREAD

**Issue by mlo0352** [lengstrom/fast-style-transfer#261]
I ran **style.py** and it terminated without error. I see some files that were created in my checkpoint directory:
`checkpoint  fns.ckpt.data-00000-of-00001  fns.ckpt.index  fns.ckpt.meta`
I cannot use any of these files to run with **evaluate.py**, however. Am I missing something? Is there something I can do to create the **.cpkt** file so I can run it?

Here's how I ran **style.py** for reference:
`python style.py --style style_image/footprints_test_1000.jpg --checkpoint-dir checkpoint_dir/ --test test_image/30073094_10160273796265076_666433414413834817_o.jpeg --test-dir test_dir/ --content-weight 1.5e1 --checkpoint-iterations 1000 --batch-size 20
`

Here's the error I get when trying to point to any of the files in the **checkpoint/** directory:
`Traceback (most recent call last):
  File "evaluate.py", line 212, in <module>
    main()
  File "evaluate.py", line 209, in main
    batch_size=opts.batch_size)
  File "evaluate.py", line 102, in ffwd
    saver.restore(sess, checkpoint_dir)
  File "/root/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/root/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "/root/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
    run_metadata)
  File "/root/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file checkpoint_dir/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?`

**Comment by RobertGoacher** [comment]
I've discovered that you can point **evaluate.py** to a directory containing a **style.py** output (the four checkpoint files you mentioned) and the script will be able to use that to render your input image. 

But I don't know how to make them into a single checkpoint file. There's no documentation for it.

**Comment by a-3isa** [comment]
Did you do this 
But I don't know how to combine those four files into a single checkpoint file like @lengstrom did. There's no documentation for it. ?????????
