### ISSUE TITLE
AssertionError: checkpoint dir not found!

### ISSUE THREAD

**Issue by ohappyboy** [lengstrom/fast-style-transfer#277]
When I run style.py：
python style.py  --style path/to/style/img.jpg --checkpoint-dir checkpoint/path  --test path/to/test/img.jpg --test-dir path/to/test/dir --content-weight 1.5e1 --checkpoint-iterations 1000 --batch-size 20
        problem：
Traceback (most recent call last):
  File "style.py", line 167, in <module>
    main()
  File "style.py", line 115, in main
    check_opts(options)
  File "style.py", line 91, in check_opts
    exists(opts.checkpoint_dir, "checkpoint dir not found!")
  File "src/utils.py", line 26, in exists
    assert os.path.exists(p), msg
AssertionError: checkpoint dir not found!

please help me，i am just a  rookie
![SB R6}`23 5ZEY`T5_V`2HR](https://user-images.githubusercontent.com/94911749/143036207-3a318933-368d-4631-ad2a-34ae906ec714.png)

**Comment by mmethot** [comment]
Maybe I'm reviving a dead thread, but to anyone asking the same question, here's what I did to resolve this:

 - Create a folder (call it w/e you want, I called it checkpoints) in the root directory of your project
 - On the command specify the newly created folder as the checkpoints folder as such:
   `--checkpoint-dir checkpoints`

**Comment by ningbogao** [comment]
The checkpoint/path is a place to add your model files !  First ,you should train NN net to get that model ,then you can use it after !
