### ISSUE TITLE
Memory runs out when training a network under python 2.7, cuda 8 on a GTX 1070 with 8GB of memory.

### ISSUE THREAD

**Issue by bryanapperson** [lengstrom/fast-style-transfer#64]
Memory runs out when training a network under python 2.7, cuda 8 on a GTX 1070 with 8GB of memory.

```
tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
Limit:                  6510195508
InUse:                  6470140160
MaxInUse:               6501474560
NumAllocs:                    1156
MaxAllocSize:           4132770816

W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************************************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 20.00MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[20,512,512]
Traceback (most recent call last):
  File "style.py", line 167, in <module>
    main()
  File "style.py", line 147, in main
    for preds, losses, i, epoch in optimize(*args, **kwargs):
  File "src/optimize.py", line 114, in optimize
    train_step.run(feed_dict=feed_dict)
  File "/opt/anaconda3/envs/style-transfer/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1550, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/opt/anaconda3/envs/style-transfer/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3764, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/opt/anaconda3/envs/style-transfer/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/opt/anaconda3/envs/style-transfer/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/opt/anaconda3/envs/style-transfer/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/opt/anaconda3/envs/style-transfer/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[20,32,32,512]
	 [[Node: sub_18 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](Relu_35, Relu_9)]]

Caused by op u'sub_18', defined at:
  File "style.py", line 167, in <module>
    main()
  File "style.py", line 147, in main
    for preds, losses, i, epoch in optimize(*args, **kwargs):
  File "src/optimize.py", line 65, in optimize
    net[CONTENT_LAYER] - content_features[CONTENT_LAYER]) / content_size
  File "/opt/anaconda3/envs/style-transfer/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 794, in binary_op_wrapper
    return func(x, y, name=name)
  File "/opt/anaconda3/envs/style-transfer/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2775, in _sub
    result = _op_def_lib.apply_op("Sub", x=x, y=y, name=name)
  File "/opt/anaconda3/envs/style-transfer/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/opt/anaconda3/envs/style-transfer/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/opt/anaconda3/envs/style-transfer/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[20,32,32,512]
	 [[Node: sub_18 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](Relu_35, Relu_9)]]
```

**Comment by bryanapperson** [comment]
```
(style-transfer) [user@system fast-style-transfer]$ conda list
# packages in environment at /opt/anaconda3/envs/style-transfer:
#
appdirs                   1.4.3                     <pip>
bazel                     0.3.1                         0    msarahan
freetype                  2.5.5                         2  
funcsigs                  1.0.2                     <pip>
jbig                      2.1                           0  
jpeg                      9b                            0  
libgfortran               3.0.0                         1  
libpng                    1.6.27                        0  
libtiff                   4.0.6                         3  
mkl                       2017.0.1                      0  
mock                      2.0.0                     <pip>
numpy                     1.12.1                   py27_0  
numpy                     1.12.1                    <pip>
olefile                   0.44                     py27_0  
openjdk                   8.17.0.3                      1    msarahan
openssl                   1.0.1k                        1  
packaging                 16.8                      <pip>
pbr                       2.0.0                     <pip>
pillow                    4.0.0                    py27_1  
pip                       9.0.1                    py27_1  
protobuf                  3.2.0                     <pip>
pyparsing                 2.2.0                     <pip>
python                    2.7.9                         3  
readline                  6.2                           2  
scipy                     0.19.0              np112py27_0  
setuptools                27.2.0                   py27_0  
setuptools                34.3.3                    <pip>
six                       1.10.0                    <pip>
sqlite                    3.13.0                        0  
system                    5.8                           2  
tensorflow                1.0.1                     <pip>
tensorflow-gpu            1.0.1                     <pip>
tk                        8.5.18                        0  
wheel                     0.29.0                    <pip>
wheel                     0.29.0                   py27_0  
xz                        5.2.2                         1  
zlib                      1.2.8                         3  
```

**Comment by lengstrom** [comment]
#16 #10

**Comment by bryanapperson** [comment]
@lengstrom - thanks for the very fast reply. Would you be amenable if I submitted a pull request wrapping this in a try/except block to catch the exception and give advice on how to proceed?
