### ISSUE TITLE
unorderable types: JpegImageFile() <= JpegImageFile()

### ISSUE THREAD

**Issue by exsstas** [lengstrom/fast-style-transfer#81]
Training starts up, work around 20 minutes, and stops with info below. I'm training with standart COCO2014 and la_muse.jpg from examples (after trying it on my own styles with a same result).
I'm not a programmer, but an artist trying to do smth with this technique, so maybe issue is very simple, but I cant figure it out by myself.

> 2017-06-07 20:24:00.474314: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
UID: 64
Epoch 0, Iteration: 1000, Loss: 1.77374e+07
style: 5.82929e+06, content:1.10176e+07, tv: 890444.0
Epoch 0, Iteration: 2000, Loss: 1.53385e+07
style: 3.99934e+06, content:1.0586e+07, tv: 753099.0
Traceback (most recent call last):
  File "style.py", line 167, in <module>
    main()
  File "style.py", line 147, in main
    for preds, losses, i, epoch in optimize(*args, **kwargs):
  File "src\optimize.py", line 105, in optimize
    X_batch[j] = get_img(img_p, (256,256,3)).astype(np.float32)
  File "src\utils.py", line 20, in get_img
    img = scipy.misc.imresize(img, img_size)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\scipy\misc\pilutil.py", line 480, in imresize
    im = toimage(arr, mode=mode)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\scipy\misc\pilutil.py", line 343, in toimage
    bytedata = bytescale(data, high=high, low=low, cmin=cmin, cmax=cmax)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\scipy\misc\pilutil.py", line 90, in bytescale
    cmin = data.min()
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\numpy\core\_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
TypeError: unorderable types: JpegImageFile() <= JpegImageFile()

**Comment by exsstas** [comment]
closed
problem was the same as in issue#54 (file  000000167126.jpg drom COCOTRAIN2014 is corruped and should be deleted)
