### ISSUE TITLE
Error while training with python 3.5

### ISSUE THREAD

**Issue by pavelkukov** [lengstrom/fast-style-transfer#98]
Hi, Thanks for sharing this really interesting project!
I'm trying to train new network with python 3.5, but I'm getting an error:
`Traceback (most recent call last):
  File "style.py", line 167, in <module>
    main()
  File "style.py", line 147, in main
    for preds, losses, i, epoch in optimize(*args, **kwargs):
  File "src\optimize.py", line 105, in optimize
    X_batch[j] = get_img(img_p, (256,256,3)).astype(np.float32)
  File "src\utils.py", line 20, in get_img
    img = scipy.misc.imresize(img, img_size)
  File "C:\Users\pavel\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Users\pavel\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\misc\pilutil.py", line 554, in imresize
    im = toimage(arr, mode=mode)
  File "C:\Users\pavel\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Users\pavel\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\misc\pilutil.py", line 380, in toimage
    bytedata = bytescale(data, high=high, low=low, cmin=cmin, cmax=cmax)
  File "C:\Users\pavel\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Users\pavel\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\misc\pilutil.py", line 93, in bytescale
    cmin = data.min()
  File "C:\Users\pavel\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\core\_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
TypeError: unorderable types: JpegImageFile() <= JpegImageFile()`

**Comment by zjiehang** [comment]
Hi!
Have you savled this problem? I have met this bug nowadays.
Thanks!

**Comment by pavelkukov** [comment]
No. The issue is with python version.
I've decided to use https://github.com/anishathalye/neural-style

**Comment by zjiehang** [comment]
Thanks for you reply!
I will turn to python 3.6 to have a try.

**Comment by zjiehang** [comment]
I find why this issue happens.
It is because the image you want to read is too large, so scipy.misc.imread return a JpegImageFile object instead of a array with many elements. The return value is also a numpy array, but it has only one element which is a JpegImageFile object .
You can preprocess the return value by this:
image = scipy.misc.imread(path)
if image.size == 1:
       image_object = a.item(0) #a_object is a JpegImageFile object 
       image_array = numpy.array(image_object)

I think why scipy.misc.imread return a object is to protect memory, so you can resize the image_object before turn it to numpy array. The class JpegImageFile has function resize and return a Image object too
Hope this can help you!

**Comment by pavelkukov** [comment]
Thanks, @zjiehang!
